name: Specs & Lint

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: MeilCli/setup-crystal-action@v4.0.3
        with:
          crystal_version: 1.0.0
          shards_version: 0.14.1
      - name: Shards install
        run: shards install
      - name: Spec
        run: crystal spec
      - name: Check formatting
        run: crystal tool format --check
