name: Specs & Lint

on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: MeilCli/setup-crystal-action@v4.4.5
        with:
          crystal_version: 1.1.1
          shards_version: 0.15.0
      - name: Shards install
        run: shards install
      - name: Spec
        run: crystal spec || exit 1
      - name: Check formatting
        run: crystal tool format --check
